// This file was generated by the storyblok CLI.
// DO NOT MODIFY THIS FILE BY HAND.
import type { ISbStoryData } from '@storyblok/js';
import type { StoryblokMultilink } from '../storyblok.d.ts';
export interface StoryblokCourse {
  category: ISbStoryData<StoryblokCourseCategory> | string;
  startDate: string;
  endDate: string;
  closed?: boolean;
  canceled?: boolean;
  seatLimit?: string;
  state?: number | string;
  bookingStateColor?: "" | "grey" | "green" | "blue" | "yellow" | "red";
  bookingStateMessage?: string;
  component: "Course";
  _uid: string;
}

export interface StoryblokCourseCategory {
  name?: string;
  discipline?: "" | "Ski" | "Snowboard";
  skillLevel?: "" | "Beginner" | "Junior_Champion" | "Champion";
  minAge?: string;
  maxAge?: string;
  priceMember?: string;
  price?: string;
  component: "CourseCategory";
  _uid: string;
}

export interface StoryblokEvent {
  date?: string;
  title?: string;
  description?: string;
  link?: Exclude<StoryblokMultilink, {linktype?: "email"} | {linktype?: "asset"}>;
  component: "Event";
  _uid: string;
}

export interface StoryblokFeature {
  name?: string;
  component: "feature";
  _uid: string;
}

export interface StoryblokGrid {
  columns?: (
    | StoryblokCourse
    | StoryblokCourseCategory
    | StoryblokEvent
    | StoryblokFeature
    | StoryblokGrid
    | StoryblokPage
    | StoryblokTeaser
  )[];
  component: "grid";
  _uid: string;
}

export interface StoryblokPage {
  body?: (
    | StoryblokCourse
    | StoryblokCourseCategory
    | StoryblokEvent
    | StoryblokFeature
    | StoryblokGrid
    | StoryblokPage
    | StoryblokTeaser
  )[];
  component: "page";
  _uid: string;
}

export interface StoryblokTeaser {
  headline?: string;
  component: "teaser";
  _uid: string;
}
